format = """
[\\[$username@$hostname $directory\\]](green) \
$git_branch$git_commit$git_state$git_status\
$cmd_duration$line_break$jobs$character"""

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[cmd_duration]
show_milliseconds = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncation_length = 8
truncate_to_repo = false

[username]
format = "[$user]($style)"
style_user = "bold green"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "bold green"
ssh_only = false

